version: '3.8'
services:
  app:
    image: docker.io/library/neo-file-locator:1.0.0-SNAPSHOT
    pull_policy: missing
    container_name: file-locator
    volumes:
      - ./:/app
    ports:
      - "8080:8080"
    depends_on:
      - neo4j

  neo4j:
    image: docker.io/library/neo4j:${NEO4J_VERSION}
    pull_policy: missing
    container_name: neo4j
    ports:
      - "${NEO4J_HTTP_PORT}:${NEO4J_HTTP_PORT}"
      - "${NEO4J_BOLT_PORT}:${NEO4J_BOLT_PORT}"
    volumes:
      - ${NEO4J_DATA_DIR}:/data
    environment:
      - NEO4J_AUTH=none